FROM ubuntu:focal

# Update packages
RUN apt-get update

# Install curl for API calls
RUN apt-get install -y curl

# Install Node.js 20
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get upgrade -y
RUN apt-get install -y nodejs

# Install Git
RUN apt-get install -y git

# Set working directory
WORKDIR /home/app

# Copy files
COPY main.sh main.sh
COPY script.js script.js
COPY package*.json ./

# Install dependencies
RUN npm install

# Make scripts executable
RUN chmod +x main.sh
RUN chmod +x script.js

# Set entrypoint
ENTRYPOINT ["/home/app/main.sh"]
